#!/bin/bash
. ./env_vars_domain
echo "Creating DNS Zone ($DOMAIN_NAME)"
az network dns zone create -g $DOMAIN_RESOURCE_GROUP -n $DOMAIN_NAME
# A record points to IP of Load balancer
echo "az network dns record-set a add-record -g $DOMAIN_RESOURCE_GROUP -z $DOMAIN_NAME -n @ -a 10.10.10.10"
# A record points to IP of Load balancer
echo "az network dns record-set a add-record -g $DOMAIN_RESOURCE_GROUP -z $DOMAIN_NAME -n * -a 10.10.10.10"
# TXT record contains a secret generated by 'centbot'
echo execute later:
echo "az network dns record-set txt add-record -g $DOMAIN_RESOURCE_GROUP -z $DOMAIN_NAME -n _acme-challenge -v certbot-secret"
